# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "PZMBQOW.SFB39388"
user = "AFJAHN"
password = "ginhob-wuDtiv-5qykce"

