# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "pzmbqow-sfb39388.snowflakecomputing.com"
user = "AFJAHN"
password = "ginhob-wuDtiv-5qykce"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
